# OpenRouter API Configuration
OPENROUTER_API_KEY = "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"

# Optional: Site configuration for OpenRouter
SITE_URL = "https://caption-generator-app.streamlit.app"
SITE_NAME = "Caption Generator App"
